[build]
  command = "CI=false npm run build"
  publish = "./public"
  build = "./build"
  base_directory = "./frontend"
  functions = "./netlify/functions"

[template.environment]
  KIETEST = "API ключ для бэкенда"
  DATABASE_URL = "PostgreSQL строка подключения"