services:
  - type: web
    name: advice-project
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    domains:
      - advice-project.onrender.com  # основной