# Generated by Django 5.1.6 on 2025-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqwe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
