# Generated by Django 5.1.6 on 2025-02-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqwe_app', '0002_alter_advice_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqwe_app.advice')),
            ],
        ),
    ]
