# Generated by Django 5.1.6 on 2025-03-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqwe_app', '0003_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('live_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
