# Generated by Django 5.1.7 on 2025-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqwe_app', '0004_stripesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
