version: '3'

services:
 web:
  build: .
  command: py manage.py runserver 0.0.0.0:8000
  ports:
   - '8000:8000'
  environment:
   - DJANGO_SETTINGS_MODULE=backend.settings
   - DEBUG=False
  volumes:
   - .:/app