"""
This type stub file was generated by pyright.
"""

brotli_installed = ...
class Compressor:
    SKIP_COMPRESS_EXTENSIONS = ...
    def __init__(self, extensions=..., use_gzip=..., use_brotli=..., log=..., quiet=...) -> None:
        ...
    
    @staticmethod
    def get_extension_re(extensions): # -> Pattern[str]:
        ...
    
    def should_compress(self, filename): # -> bool:
        ...
    
    def log(self, message): # -> None:
        ...
    
    def compress(self, path): # -> list[Any]:
        ...
    
    @staticmethod
    def compress_gzip(data): # -> bytes:
        ...
    
    @staticmethod
    def compress_brotli(data):
        ...
    
    def is_compressed_effectively(self, encoding_name, path, orig_size, data): # -> Literal[False]:
        ...
    
    def write_data(self, path, data, suffix, stat_result):
        ...
    


def main(argv=...): # -> Literal[0]:
    ...

if __name__ == "__main__":
    ...
