"""
This type stub file was generated by pyright.
"""

class MediaTypes:
    __slots__ = ...
    def __init__(self, *, extra_types: dict[str, str] | None = ...) -> None:
        ...
    
    def get_type(self, path: str) -> str:
        ...
    


def default_types() -> dict[str, str]:
    """
    We use our own set of default media types rather than the system-supplied
    ones. This ensures consistent media type behaviour across varied
    environments.  The defaults are based on those shipped with nginx, with
    some custom additions.

    (Auto-generated by scripts/generate_default_media_types.py)
    """
    ...

